version: "3.7"
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    env_file:
      - .envdb
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000    
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev

