# Generated by Django 3.1.7 on 2021-12-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
